name: Create Terraform Cloud Workspace

description: Creates a Terraform Cloud workspace

inputs:
  tfcToken:
    description: A Terraform Cloud API token with access to manage workspaces
    required: true

  orgName:
    description: The name of the Terraform Cloud organization in which to create the workspace
    required: true

  workspaceName:
    description: The name of the Terraform Cloud workspace
    required: true

  terraformVersion:
    description: The version of Terraform that the workspace should be configured to run
    required: false

runs:
  using: docker
  image: Dockerfile

branding:
  icon: arrow-up-right
  color: blue
